/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewsAluno;

import DAO.AlunoDAO;
import DAO.Conexao;
import DAO.EmprestimoDAO;
import DAO.LivroDAO;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.sound.midi.SysexMessage;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Aluno;
import model.Emprestimo;
import model.Livro;
import viewsAdmin.VisuLivro;

/**
 *
 * @author Alan Nascimento
 */
public class EmprestimoAluno extends javax.swing.JDialog {

    /**
     * Creates new form Reservas
     */
    Principal telaPrincipal;
    private String matriculaAluno="1";
    Livro livroSelec;
    String titulo;
    int linSelected;

    public EmprestimoAluno(java.awt.Frame parent, boolean modal, Aluno alunoLoga) {
        super(parent, modal);
        initComponents();
        this.matriculaAluno=alunoLoga.getMatricula();
        telaPrincipal = (Principal) parent;
        preencheTabela();
    }
    
    public void limpaCampos(){
        jLIsbn.setText("-");
        jLDevolucao.setText("-");
        jLEmprestimo.setText("-");
    }
    public void preencheTabela(){
        Connection conexao = Conexao.conectar();
        EmprestimoDAO emprestimoDAO = new EmprestimoDAO(conexao);
        AlunoDAO alunoDAO = new AlunoDAO(conexao);
        LivroDAO livroDAO = new LivroDAO(conexao);
        List<Emprestimo> listaEmprestimo = new ArrayList<>();
        
        DefaultTableModel model = (DefaultTableModel) tabelaLivros.getModel();
        model.setNumRows(0);
        int i = 0;
        Aluno aluno = alunoDAO.selecionarAluno(alunoDAO.retornaIdAluno(matriculaAluno));
        listaEmprestimo = emprestimoDAO.listarEmprestimo(aluno.getId());
        Livro livro;
        
        //jLNome.setText(aluno.getNome());
        //jLMatricula.setText(aluno.getMatricula());
        for(Emprestimo e : listaEmprestimo){
            model.addRow(new String[i]);
            livro = livroDAO.selecionarLivro(e.getIdLivro());
            tabelaLivros.setValueAt(livro.getTitulo(), i, 0);
            tabelaLivros.setValueAt(livro.getDescricao(), i, 1);
            i++;
        }
        Conexao.desconectar(conexao);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLivros = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLIsbn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLEmprestimo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLDevolucao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(194, 194, 194));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cadastrar_Reserva.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Minhas Reservas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabelaLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Título", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaLivros.getTableHeader().setReorderingAllowed(false);
        tabelaLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaLivrosMouseClicked(evt);
            }
        });
        tabelaLivros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelaLivrosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaLivros);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/renovar.png"))); // NOI18N
        jButton1.setText("Renovar");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/devolver.png"))); // NOI18N
        jButton2.setText("Devolver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLIsbn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLIsbn.setText("-");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("ISBN:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Data Empréstimo:");

        jLEmprestimo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLEmprestimo.setText("-");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Data Devolução:");

        jLDevolucao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLDevolucao.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLIsbn)
                    .addComponent(jLabel4)
                    .addComponent(jLEmprestimo)
                    .addComponent(jLabel5)
                    .addComponent(jLDevolucao)
                    .addComponent(jLabel7))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaLivrosMouseClicked
        if(evt.getClickCount() == 2){
            linSelected = tabelaLivros.getSelectedRow();
            titulo = (tabelaLivros.getValueAt(linSelected, 0).toString());
            livroSelec = new Livro();
            
            Connection conexao = Conexao.conectar();
            LivroDAO livroDAO = new LivroDAO(conexao);
            AlunoDAO alunoDAO = new AlunoDAO(conexao);
            
            EmprestimoDAO emprestimoDAO = new EmprestimoDAO(conexao);
            livroSelec = livroDAO.selecionarLivro(livroDAO.retornaIdLivro(titulo));
            Emprestimo emp = emprestimoDAO.getEmprestimo(alunoDAO.retornaIdAluno(matriculaAluno),livroDAO.retornaIdLivro(livroSelec.getIsbn()));
            jLEmprestimo.setText(emp.getDataInicio().toString());
            jLDevolucao.setText(emp.getDataFim().toString());
            Conexao.desconectar(conexao);
            
            jLIsbn.setText(livroSelec.getIsbn());
        }
    }//GEN-LAST:event_tabelaLivrosMouseClicked

    private void tabelaLivrosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaLivrosKeyPressed

    }//GEN-LAST:event_tabelaLivrosKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Connection conexao = Conexao.conectar();
        EmprestimoDAO emprestimoDAO = new EmprestimoDAO(conexao);
        AlunoDAO alunoDAO = new AlunoDAO(conexao);
        LivroDAO livroDAO = new LivroDAO(conexao);
        if(livroSelec!= null){
            emprestimoDAO.delEmprestimo(alunoDAO.retornaIdAluno(matriculaAluno),livroDAO.retornaIdLivro(livroSelec.getIsbn()));
            JOptionPane.showMessageDialog(rootPane, "Devolvido", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha da tabela", "ERRO", JOptionPane.ERROR_MESSAGE);  
        }
        limpaCampos();
        Conexao.desconectar(conexao);
        preencheTabela();
        livroSelec=null;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection conexao = Conexao.conectar();
        EmprestimoDAO emprestimoDAO = new EmprestimoDAO(conexao);
        AlunoDAO alunoDAO = new AlunoDAO(conexao);
        
        LivroDAO livroDAO = new LivroDAO(conexao);
        if(livroSelec!=null){
            Date newData = new Date();
            livroSelec = livroDAO.selecionarLivro(livroDAO.retornaIdLivro(titulo));
            Emprestimo emp = emprestimoDAO.getEmprestimo(alunoDAO.retornaIdAluno(matriculaAluno),livroDAO.retornaIdLivro(livroSelec.getIsbn()));
            
            long dt = (emp.getDataFim().getTime() - emp.getDataInicio().getTime()) + 3600000; // 1 hora para compensar horário de verão
            long diasPassados = (dt / 86400000L); // passaram-se 67111 dias
            
            
            if(diasPassados<22){
                emp.getDataFim().setDate(emp.getDataFim().getDate()+7);
                emprestimoDAO.delEmprestimo(alunoDAO.retornaIdAluno(matriculaAluno), livroDAO.retornaIdLivro(livroSelec.getIsbn()));
                emprestimoDAO.addEmprestimo(emp);
                JOptionPane.showMessageDialog(rootPane, "Renovado", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);

            }else{
                JOptionPane.showMessageDialog(rootPane, "Não é possível a renovação, limite excedido!", "ERRO", JOptionPane.ERROR_MESSAGE);          
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha da tabela", "ERRO", JOptionPane.ERROR_MESSAGE);  
        }
        limpaCampos();
        preencheTabela();
        livroSelec=null;
        Conexao.desconectar(conexao);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmprestimoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmprestimoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmprestimoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmprestimoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EmprestimoAluno dialog = new EmprestimoAluno(new javax.swing.JFrame(), true, new Aluno());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLDevolucao;
    private javax.swing.JLabel jLEmprestimo;
    private javax.swing.JLabel jLIsbn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaLivros;
    // End of variables declaration//GEN-END:variables
}
